# .github/workflows/ci.yml

name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# modifications to .github/workflows/ci.yml

jobs:
  docker-hub:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build and Push an Image to Docker Hub
      - name: Build and push
        env:
          DOCKERHUB_REPO: parsajalilifar/fragments-ui
          SHA_TAG: sha-${{ github.sha }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKERHUB_REPO }}:latest
